package Interface;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.IOException;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

import javax.swing.JFileChooser;

import java.io.ByteArrayOutputStream;
import java.io.File;
import Agent_communication.file;
import Agent_communication.users;
import Domaine.AgentInfo;
import jade.core.AID;
import jade.core.Agent;
import jade.core.ProfileImpl;
import jade.core.Runtime;
import jade.domain.AMSService;
import jade.domain.FIPAAgentManagement.AMSAgentDescription;
import jade.domain.FIPAAgentManagement.SearchConstraints;
import jade.gui.GuiEvent;
import jade.lang.acl.ACLMessage;
import jade.wrapper.AgentContainer;
import jade.wrapper.AgentController;
import jade.wrapper.ControllerException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrateur
 */
@SuppressWarnings("serial")
public class Index extends javax.swing.JFrame {
	// definie les deux types d'agents
	public static AgentInfo informaticien;
	public static Agent mathematicien;

	public static String nomAgent;
	public static String prenomAgent;
	public static String domaineAgent;
	public static String mtpAgent;
	public static int id;
	String nom = "";

	/**
	 * Creates new form Index
	 */
	public Index() {
		initComponents();
		this.setVisible(true);
	}

	static void récuperation(String nomAgen, String prenomAgen, String domaineAgen, String mtpAgen) {

		nomAgent = nomAgen;
		prenomAgent = prenomAgen;
		domaineAgent = domaineAgen;
		mtpAgent = mtpAgen;
	}

	static void affecterAgentMath(Agent agent) {
		mathematicien = agent;

	}
	// ajouter l'utilisteur comme agent
	// cree un container pour cet agent
	static void affecterAgentInfo(AgentInfo agent, int id) {
		informaticien = agent;
	
		//informaticien=AgentInfo.getMesAgents().elementAt(id).a;
		Index.id = id;
	//	System.out.println("ppppppppp "+agent.getAID().getName());
		System.out.println("taille " + users.getInfo().size());

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTabbedPane4 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		button2 = new java.awt.Button();
		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jPanel4 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		button1 = new java.awt.Button();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Index");

		jPanel1.setBackground(new java.awt.Color(255, 204, 204));

		jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		jLabel1.setText("Bienvenu " + nomAgent + " Dans Votre Espace Personnel ");

		jTabbedPane4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jPanel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel12.setText("Prénom : " + prenomAgent);
		jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		jLabel13.setText("Informations de profil");

		jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel14.setText("Centre d'intérêt : " + domaineAgent);
		jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel15.setText("Nom : " + nomAgent);
		jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jButton4.setText("Modifier Profil");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/hello (1).png"))); // NOI18N

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(102, 102, 102)
						.addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 288,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 266,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(85, 85, 85))
								.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel16)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout.createSequentialGroup()
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel17).addGap(0, 0, Short.MAX_VALUE))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
														.createSequentialGroup()
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45,
																Short.MAX_VALUE)
														.addGroup(jPanel2Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel12,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 266,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel15,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 266,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel14,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 266,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jButton4,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 266,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(95, 95, 95))))))));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(113, 113, 113).addComponent(jLabel16))
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(146, 146, 146)
												.addComponent(jLabel17))
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(46, 46, 46)
												.addComponent(jLabel13)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGap(10, 10, 10))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addComponent(jLabel18,
								javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		jTabbedPane4.addTab("Acceuil", jPanel2);

		jPanel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		button2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		button2.setLabel("Parcourir...");
		button2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button2ActionPerformed(evt);
			}

		});
		jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
		jLabel3.setText("Contacts");

		jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
		jLabel2.setText("Documents envoyés");

		jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel6.setText("Description");

		jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel7.setText("Nom fichier");

		jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jButton3.setText("Retourner");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}

			
		});
		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		if (domaineAgent == "Informatique") {

			for (int i = 0; i < users.getInfo().size(); i++) {
				if (i != id)
					nom = nom + users.getInfo().get(i).getUser().getNom() + " "
							+ users.getInfo().get(i).getUser().getPrenom() + "\n";

			}
			jTextArea1.setText(nom);
			// System.out.println("agents "+ informaticien.mesAgents.size());

			jScrollPane1.setViewportView(jTextArea1);
		}

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup().addGap(100, 100, 100).addComponent(jLabel3))
						.addGroup(jPanel3Layout.createSequentialGroup().addGap(52, 52, 52).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(39, 39, 39)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(
										jPanel3Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel2)))
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93,
												Short.MAX_VALUE)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 111,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 108,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 167,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 167,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(62, 62, 62))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(jPanel3Layout.createSequentialGroup()
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE,
																298, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel3Layout.createSequentialGroup().addGap(96, 96, 96)
														.addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
												.addGap(45, 45, 45)))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jLabel2))
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(27, 27, 27)
										.addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(47, 47, 47)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168,
														Short.MAX_VALUE)
												.addComponent(jScrollPane2))))
						.addGap(26, 26, 26).addComponent(jButton3).addGap(0, 80, Short.MAX_VALUE)));

		jTabbedPane4.addTab("Boîte d'envoi", jPanel3);

		jPanel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
		jLabel8.setText("Documents reçus");

		jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		//jLabel10.setText("gggggggggg");

		jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
		jLabel11.setText("Contacts");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(
								jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 286,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(137, 137, 137))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
						.addGap(178, 178, 178)
						.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 139,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
						.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 285,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(127, 127, 127))
				.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addGap(104, 104, 104)
								.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 286,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(509, Short.MAX_VALUE))));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap(22, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(jLabel11))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 272,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel4Layout.createSequentialGroup().addContainerGap(74, Short.MAX_VALUE)
								.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 272,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(15, 15, 15))));

		jTabbedPane4.addTab("Boîte de réception", jPanel4);

		button1.setBackground(new java.awt.Color(153, 153, 153));
		button1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		button1.setLabel("Déconnexion");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button1ActionPerformed(evt);
			}
		});
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
												.addComponent(jTabbedPane4))
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(37, 37, 37)
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(25, 25, 25)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(61, Short.MAX_VALUE)
										.addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(34, 34, 34)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTabbedPane4,
								javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		jTabbedPane4.getAccessibleContext().setAccessibleName("Boite d'envoi");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	// modification de l'utilisateur
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Modification.Mrécuperation(nomAgent, prenomAgent, domaineAgent, mtpAgent);

		new Modification();
		this.dispose();
		this.setVisible(false);

	}

	private void Button2ActionPerformed(ActionEvent evt) {
		//System.out.println("index taille " + AgentInfo.getMesAgents().size());
		ACLMessage message = new ACLMessage(ACLMessage.INFORM);
		/* init du filechooser */
		JFileChooser fc = new JFileChooser();
		file file = new file();
		/* affichage du dialog et test si le bouton ok est pressé */
		if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
			// recupération de fichier
			if (fc.getSelectedFile() != null) {
				String filename = fc.getSelectedFile().getName();
				jTextField2.setText(filename);
				FileInputStream fis;
				byte[] bytes = null;
				try {
					fis = new FileInputStream(fc.getSelectedFile());
					ByteArrayOutputStream bos = new ByteArrayOutputStream();
					byte[] buf = new byte[1024];
					for (int readNum; (readNum = fis.read(buf)) != -1;) {
						bos.write(buf, 0, readNum);
					}
					bytes = bos.toByteArray();
				} catch (FileNotFoundException ex) {
					// Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
				} catch (IOException ex) {
					// Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
					ex.printStackTrace();
				}
				file.setF(bytes);
				file.setFileName(filename);
				String desc = jTextField3.getText().toString();
				file.setDescription(desc);
				String a=jTextArea2.getText().toString();
				jTextArea2.setText(a+"\n"+file.getFileName());
			}

		}
		try {
			// récupere le message
			message.setContentObject(file);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		AgentInfo.setFiles(file);
		Agent b = null;
		int i = 0;
		/*if (informaticien != null) {
			while (i < users.getInfo().size()) {
				if (i != id) {
					b = users.getInfo().get(i);
				}
				i++;
			}

		}*/
		
			/* message.addReceiver(new AID("rma", AID.ISLOCALNAME)); 
			informaticien.send(message);*/
		 
		
		System.out.println("foooooooor " + AgentInfo.rec);
		// message.addReceiver(AgentInfo.class.getM);
	

	}
	
	private void jButton3ActionPerformed(ActionEvent evt) {
		new Index();
		this.setVisible(false);
		this.dispose();
		
	}
	private void button1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		this.setVisible(false);
		new Connexion();
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Index().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private java.awt.Button button1;
	private java.awt.Button button2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTabbedPane jTabbedPane4;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration
}
